# Generated by Django 4.0.5 on 2022-06-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='historicalgroup',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Группа', 'verbose_name_plural': 'historical Группы'},
        ),
        migrations.AlterField(
            model_name='group',
            name='leader',
            field=models.ManyToManyField(to='taskapi.employer', verbose_name='Тимлид'),
        ),
    ]
